#数据库配置信息
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 10
#指定mapper文件位置
mybatis:
  mapper-location:  classpath:mapper/*.xml
  mapper-base-package: cn.hqu.csmall.passport.mapper

# MyBatis-Plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#启用knife4j
knife4j:
  enable: true
  base-package: cn.hqu.csmall.passport.controller
  group-name: passport
  host: http://localhost:9181
  title: 酷鲨商城在线API文档
  description: 酷鲨商城-管理员认证与授权
  contact-name: tedu
  contact-url: http://www.tedu.cn
  contact-email: java@tedu.cn

#服务器端口
server:
  port: 9181
