#数据库配置信息
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 10
#指定mapper文件位置
mybatis:
  mapper-location:  classpath:mapper/*.xml

#启用knife4j
knife4j:
  enable: true

#服务器端口
server:
  port: 9181
