#数据库配置信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_ams?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 20050806

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    cn.hqu.csmall.passport:  trace

server:
  port: 9181

csmall:
  jwt:
    secret-key: sadsadvojsnanjdsoikppsalcmoaskmqfwqsdkzmalvkspncdksakbfaisbadscwcxzaldwvdcsnas
    expire-in-minute: 43200