#数据库配置信息
spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 10
#指定mapper文件位置
mybatis:
  mapper-location:  classpath:mapper/*.xml
  mapper-base-package: cn.hqu.csmall.product.mapper

#启用knife4j
knife4j:
  enable: true
  base-package: cn.hqu.csmall.product.controller
  group-name: product
  host: http://localhost:9181
  title: 酷鲨商城在线API文档--商品管理
  description: 酷鲨商城-商品管理
  contact-name: tedu
  contact-url: http://www.tedu.cn
  contact-email: java@tedu.cn
