spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_promotion?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 20050806
logging:
  level:
    cn.hqu.csmall.marketing: trace
